
post http://localhost:8080/api/users/login
Content-Type: application/json

{
    "email":"james@gmail.com",
    "password":"1234567"
}

###
post http://localhost:8080/api/users/signup
Content-Type: application/json

{
    "email":"nolan@gmail.com",
    "name":"nolan",
    "password":"1234567"
}

###



get http://localhost:8080/api/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWE4MjA1ZTNjYjJiNDFjN2VhODM1YSIsImlhdCI6MTY3MjA4NDI1NCwiZXhwIjoxNjcyMDkxNDU0fQ.ukgcBWB6AcI1OJgFLyCWU3xK-8GWsgk2w_PA63Jb2Mw



###

put http://localhost:8080/api/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWIzZjE3YmYyNDY1OThkMmYxOTgzZiIsImlhdCI6MTY3MjMyOTk2NCwiZXhwIjoxNjcyMzM3MTY0fQ.Ow35hzBhmT67w6apjXdHOQI8om6SurObGDSco1hwHL8

{   

    "desc":"Im a marine biologist",
    "occupation":"Biologist"
}

###

post http://localhost:8080/api/users/refresh-token
Content-Type: application/json

{   
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWE4MjA1ZTNjYjJiNDFjN2VhODM1YSIsImlhdCI6MTY3MjA3NTg1NiwiZXhwIjoxNjcyMzM1MDU2fQ.Ren0qgxEtWYGdOR8EIQHbR2WY1GwFUr1_pV9voNfuZ8"
   
}   

###
get  http://localhost:8080/api/users/639a8205e3cb2b41c7ea835a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWE4MjA1ZTNjYjJiNDFjN2VhODM1YSIsImlhdCI6MTY3MjMyNDc4NiwiZXhwIjoxNjcyMzMxOTg2fQ.aj_XflktNMqYxxkRe935_3H5y4grETly-MJj6kZ2dbw

//create post and project
###
post http://localhost:8080/api/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWE4MjA1ZTNjYjJiNDFjN2VhODM1YSIsImlhdCI6MTY3MjQ0OTI1MiwiZXhwIjoxNjcyNDU2NDUyfQ.7PELIHh7s2hSI9seiJAE1908SkdXsI3dg6dbbd1oNFI

{
   
    "desc":"Sound is an individual perception",
    "img":"",
    "projectName":"The colours of might",
    "maxMembers":"2"
}
###
get  http://localhost:8080/api/posts/63aa06c650dbe6ba10e81f6c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWE4MjA1ZTNjYjJiNDFjN2VhODM1YSIsImlhdCI6MTY3MjI1NDkwMiwiZXhwIjoxNjcyMjYyMTAyfQ.Zpb7nj5dCiIbXlpbO0y2WVrbug-odrdx1lnbxyThkRI

###
get http://localhost:8080/api/posts/all
Content-Type: application/json'

### 
get  http://localhost:8080/api/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWIzZTlkZjY0ZThiYWYyOTc2ZDE1OSIsImlhdCI6MTY3MjQyNTkyNSwiZXhwIjoxNjcyNDMzMTI1fQ.bmNyPxkWRZAr8lmZsJf-_qikgHqxDJp4ixDdM4QPNeY

###

put  http://localhost:8080/api/posts/63aa06c650dbe6ba10e81f6c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWE4MjA1ZTNjYjJiNDFjN2VhODM1YSIsImlhdCI6MTY3MjI1NDkwMiwiZXhwIjoxNjcyMjYyMTAyfQ.Zpb7nj5dCiIbXlpbO0y2WVrbug-odrdx1lnbxyThkRI

{
 
    "desc":"Belive in the word of god"
    
}

###
delete  http://localhost:8080/api/posts/63af64a17abf62df9ef69ef7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWE4MjA1ZTNjYjJiNDFjN2VhODM1YSIsImlhdCI6MTY3MjQzODg4NSwiZXhwIjoxNjcyNDQ2MDg1fQ._B5Bwhgfr1SHkFJPb8hEnGY3B_RlThEi5VOwOM4-Zv4




###
put  http://localhost:8080/api/users/changepassword 
Content-Type: application/json

{
    "email":"jeff@gmail.com",
    "password":"1234567"
}

###
post http://localhost:8080/api/join/63af95b4728c0ed2f6d8c708
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWIzZTlkZjY0ZThiYWYyOTc2ZDE1OSIsImlhdCI6MTY3MjQ5NjM4OSwiZXhwIjoxNjcyNTAzNTg5fQ.s1crEjcNw3-9hZUAZjGDsGKjqinhGWXkcA55QUdJD-o


###
get http://localhost:8080/api/join/63af95b4728c0ed2f6d8c708
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWIzZTlkZjY0ZThiYWYyOTc2ZDE1OSIsImlhdCI6MTY3MjUxMzYzNCwiZXhwIjoxNjcyNTIwODM0fQ.AzzRYgzsB8-obZ-exqh8xrhF1KIXnKWa1KKlqKaG0i4


###
delete http://localhost:8080/api/join/63af464f448dad0d5f9ed43b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWE4MjA1ZTNjYjJiNDFjN2VhODM1YSIsImlhdCI6MTY3MjQyMjM4OCwiZXhwIjoxNjcyNDI5NTg4fQ.8L7WUj5DkvaQtZ4Hdw6fbbwr1YAw1NUKLqRfYCENiao

###
put http://localhost:8080/api/join/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWE4MjA1ZTNjYjJiNDFjN2VhODM1YSIsImlhdCI6MTY3MjUxMzg1MSwiZXhwIjoxNjcyNTIxMDUxfQ.CO8UOgGz2vfb0OEs5YUMnckkBV3QCDXKikfG8Y-U2s0

{
    "postId":"63af95b4728c0ed2f6d8c708",
    "joinId":"63b045a48ff55f8e6f28ab80",
    "status":"Accept"
}

//project endpoints
###

###
get http://localhost:8080/api/project/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWIzZjE3YmYyNDY1OThkMmYxOTgzZiIsImlhdCI6MTY3MjQ0NTA1MiwiZXhwIjoxNjcyNDUyMjUyfQ.WrmYgCb8hMqxYAsYZ7oP4zGnhA4XkaXrOxdVRYOjy-Q

### 
get http://localhost:8080/api/project/all
Content-Type: application/json

###
delete http://localhost:8080/api/project/63adf011b63ecc9ab42cb380
Content-Type: application/json

###
put http://localhost:8080/api/project/63af95b4728c0ed2f6d8c70a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWE4MjA1ZTNjYjJiNDFjN2VhODM1YSIsImlhdCI6MTY3MjQ5NjEzMiwiZXhwIjoxNjcyNTAzMzMyfQ.nhUNmuIr6XPxT9Wd6-p36oEcWiNAeL-BRXuYUxxiGv8

{
    "projectName":"The ultimate Students",
    "desc":"make me better",
    "maxMembers": 2
}

###
put http://localhost:8080/api/project/startproject/63af95b4728c0ed2f6d8c70a
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWE4MjA1ZTNjYjJiNDFjN2VhODM1YSIsImlhdCI6MTY3MjUxMzg1MSwiZXhwIjoxNjcyNTIxMDUxfQ.CO8UOgGz2vfb0OEs5YUMnckkBV3QCDXKikfG8Y-U2s0

###
delete http://localhost:8080/api/project/exitproject/63af95b4728c0ed2f6d8c70a
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWIzZTlkZjY0ZThiYWYyOTc2ZDE1OSIsImlhdCI6MTY3MjUxMzYzNCwiZXhwIjoxNjcyNTIwODM0fQ.AzzRYgzsB8-obZ-exqh8xrhF1KIXnKWa1KKlqKaG0i4

###
delete http://localhost:8080/api/project/removeuser/63af95b4728c0ed2f6d8c70a
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWE4MjA1ZTNjYjJiNDFjN2VhODM1YSIsImlhdCI6MTY3MjUxMzg1MSwiZXhwIjoxNjcyNTIxMDUxfQ.CO8UOgGz2vfb0OEs5YUMnckkBV3QCDXKikfG8Y-U2s0

{
    "userId":"63ab3e9df64e8baf2976d159"
}